[package]
name = "ryzen-reader"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "GPL-2.0+"
description = "Read cpu power usage from AMD ryzen cpus on linux"

[dependencies]
thiserror = "1.0"